"""API router registry."""
from nexus.api.routers import (
    accounts,
    admin_billing,
    admin_billing_write,
    admin_users,
    admin_jobs,
    admin_provider_keys,
    admin_sources,
    admin_health,
    billing_webhooks,
    agents,
    alerts,
    auth,
    billing,
    cadences,
    calling,
    campaigns,
    chat,
    contacts,
    custom_fields,
    integrations,
    network,
    orchestration,
    outcomes,
    relevance,
    signals,
    workflow,
    workspace,
)

all_routers = [
    auth.router,
    relevance.router,
    accounts.router,
    contacts.router,
    agents.router,
    workflow.router,
    campaigns.router,
    cadences.router,
    calling.router,
    alerts.router,
    integrations.router,
    network.router,
    workspace.router,
    signals.router,
    orchestration.router,
    chat.router,
    custom_fields.router,
    outcomes.router,
    admin_billing.router,
    admin_billing_write.router,
    admin_jobs.router,
    billing.router,
    billing_webhooks.router,
    admin_users.router,
    admin_provider_keys.router,
    admin_sources.router,
    admin_health.router,
]

__all__ = ["all_routers"]
