"""Baseline schema — create all NEXUS tables from the current model metadata.

This is the initial migration. It materializes every registered model so a fresh database can be
stamped/migrated to ``head``. Subsequent schema changes should be added as autogenerated revisions
(``alembic revision --autogenerate``), not by editing this file.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-01
"""
from __future__ import annotations

from alembic import op

import nexus.models  # noqa: F401  (register all mappers)
from nexus.core.db import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
