#!/usr/bin/env bash
# NEXUS GTM — Azure deployment environment.
#
#   cp deploy/cloud/azure/azure-env.example.sh ~/nexus-env.sh
#   code ~/nexus-env.sh          # fill in every REPLACE_ value
#   source ~/nexus-env.sh
#
# RE-SOURCE THIS AFTER EVERY CLOUD SHELL RECONNECT. Cloud Shell drops environment variables on
# idle timeout while keeping your files, so a session that "still has everything open" can be
# missing every value here. Deploys have been lost to exactly that (issue D3): TF_VAR_secrets
# silently empty, and Terraform happily planning an estate with no credentials in it.
#
# CONTAINS NO SECRETS, deliberately. Application secrets live in deploy/.env (gitignored) and are
# generated by deploy.sh; Azure credentials come from `az login`. Nothing here is worth stealing,
# which is what makes it safe to keep in your Cloud Shell home directory.

# ============================== Identity ==============================
# az account show --query id -o tsv
export AZURE_SUBSCRIPTION_ID="REPLACE_WITH_YOUR_SUBSCRIPTION_ID"

# ============================== Naming ==============================
# PROJECT prefixes every Azure resource: nexus-prod-rg, nexus-prod-app, ...
# Changing it after deploying renames everything, which is a rebuild. Decide once.
export PROJECT="nexus"

# VERIFY THIS REGION BEFORE USING IT — do not trust the default.
#
# PostgreSQL Flexible Server provisioning is RESTRICTED in some regions on some subscriptions, and
# Azure reports that as `400 ... 'Version' should be in: []` — an EMPTY list that reads as
# "PostgreSQL 16 is unsupported" and sends you off to change the version. It is not the version.
# A healthy region returns tens of thousands of bytes here; a restricted one, a few hundred:
#
#   for r in eastus eastus2 centralus westus3; do \
#     echo "$r: $(az postgres flexible-server list-skus -l $r -o json | wc -c) bytes"; done
#
# Everything is regional and the database must share a region with its delegated subnet, so
# changing this after deploying means rebuilding the whole stack.
export AZURE_LOCATION="eastus2"

# ============================== Domain ==============================
export DOMAIN="gtm.infojoy.com"
export STAGING_DOMAIN="staging-gtm.infojoy.com"

# ============================== Operations ==============================
# NOT COSMETIC. Empty leaves the Azure action group with ZERO RECIPIENTS, so the metric alert
# fires into the void — while the portal still shows an alert rule, which reads as configured.
# That is strictly worse than having no alert, because it buys false confidence (issue G7).
export ALARM_EMAIL="REPLACE_WITH_YOUR_OPS_EMAIL"

# ============================== Admin access ==============================
# The Control plane (/admin) allowlist. AT MOST TWO ENTRIES — a policy limit, not a technical one;
# beyond two an allowlist stops being a restriction and becomes a list. Use a CIDR range for an
# office network (e.g. 203.0.113.0/24).
#
# Applied through the Control plane UI (Runtime settings -> admin_ip_allowlist), NOT through
# Terraform: the value lives in the runtime_settings table so it can be corrected without a
# deploy — which matters, because the only place to fix a bad allowlist is the panel it just
# closed. Empty means open; a malformed list is ignored rather than enforced, for the same reason.
export ADMIN_IP_1="203.199.234.154"
export ADMIN_IP_2="REPLACE_OR_LEAVE_BLANK"

# ============================== Terraform state ==============================
export TFSTATE_RG="nexus-tfstate-rg"
# GLOBALLY UNIQUE across all of Azure. 3-24 characters, lowercase letters and digits only.
# Part 5 of the deploy guide generates one and rewrites this line for you.
export TFSTATE_SA="REPLACE_IN_PART_5"
export TFSTATE_CONTAINER="tfstate"

# ============================== Derived — do not edit ==============================
export PROD_RG="${PROJECT}-prod-rg"
export STAGING_RG="${PROJECT}-staging-rg"
export PROD_APP="${PROJECT}-prod-app"
export PROD_WORKER="${PROJECT}-prod-worker"
export STAGING_APP="${PROJECT}-staging-app"
export STAGING_WORKER="${PROJECT}-staging-worker"

# ============================== Filled in after Part 7 ==============================
# deploy.sh prints these; the guide appends them to your copy of this file.
#   export PROD_URL=...      the *.azurecontainerapps.io ingress
#   export PROD_FQDN=...     CNAME target for gtm.infojoy.com
#   export ACR_NAME=...      SHARED by staging — both pipelines need it
#   export STAGING_URL=...

# ============================== Not set here, on purpose ==============================
#
# TF_VAR_secrets            built by deploy.sh from deploy/.env at run time. Exporting it by hand
#                           is how a stale value from a previous shell reaches a later apply.
# POSTGRES_PASSWORD         generated by deploy.sh (24 random bytes) and written into Terraform
# NEXUS_APP_DB_PASSWORD     state. Never typed, never reused, never in a file you edit — and
# NEXUS_SECRET_KEY          NEVER left as CHANGE_ME, which deploy.sh refuses to pass through
#                           after it once shipped as the live Postgres admin password and the
#                           JWT signing key. Neither fails loudly; both are in the repository.
